import type { Metadata } from 'next';
import { lato, italianno, SplineSansMono } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${italianno.variable} ${SplineSansMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
